### PR TITLE
Support modify comment

### PR DESCRIPTION
**Pull request by smallx**
Support modify comment, for Doris https://github.com/apache/doris/pull/39783

### CODE REVIEW

**Review by w41ter — APPROVED** [review]

**Comment by w41ter** [comment]
Hi, @smallx, sorry to have kept you waiting for so long. Since the old ccr syncer cannot recognize the newly added binlog type, I plan to merge the PRs for adding these binlog types after the next version (doris 2.1.6) is released.

BTW, are you willing to add regression tests for these newly added binlog types?

**Comment by smallx** [comment]
@w41ter Okay, I'll add some test cases.

**Comment by smallx** [comment]
add regression tests: done

**Comment by w41ter** [comment]
@smallx please resolve the conflicts.

**Comment by smallx** [comment]
@w41ter rebased branch dev

**Review by w41ter — APPROVED** [review]

**Pull request merged**
