### PR TITLE
Support drop view

### PR DESCRIPTION
**Pull request by smallx**
Support drop view, for Doris https://github.com/apache/doris/pull/39781

### CODE REVIEW

**Review by w41ter — APPROVED** [review]

**Comment by w41ter** [comment]
Hi @smallx, please resolve the confliction.

**Comment by smallx** [comment]
Hi @w41ter, rebased branch dev.

**Comment by smallx** [comment]
@w41ter I found `test_view_and_mv.groovy` has been removed. Do we still need these test cases? Can I delete this file?

**Comment by w41ter** [comment]
@smallx delete it, I will add a new test file for dropping view later

**Review by w41ter — APPROVED** [review]

**Comment by w41ter** [comment]
I think this PR is ready to be merged. I'll open a new PR to handle the test file.

**Comment by smallx** [comment]
Okay, thank you very much @w41ter

**Pull request merged**
